### ISSUE TITLE
[PE-D][Tester B] Tree does not update in real time

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2103T-W11-4/tp#153]
Both when adding new teams and adding new developers to teams the tree does not update visually and has to be reloaded to reflect the changes.
![image.png](https://raw.githubusercontent.com/alvinlim277/ped/main/files/c6fe4976-e82d-4aa5-8c71-7b155815c957.png)
![image.png](https://raw.githubusercontent.com/alvinlim277/ped/main/files/16c9a4da-6e9b-4186-88d9-9ca41fb29799.png)

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: alvinlim277/ped#5

**Comment by Tang-Moyan** [comment]
The content in the tree will not be updated in real time because that requires too much computer resources. Instead, the tree is updated every time you show it. So, when you have some changes to the data, you should hide the tree first if it is shown, and call command tree again to show the tree. Then your changes will be reflected in the new tree. With that being said, if you enter the command tree to show LinkTree and make some changes to the data, your changes will not be reflected in the current tree. You should hide the tree first and then call tree again to obtain a new tree which will reflect the changes you made.

This should note be considered as a bug. However, it is reflected as note in UG.
